### ISSUE TITLE
长时间不收到数据，则会异常，且无法重连

### ISSUE THREAD

**Issue by xzc-coder** [thridparty-cloud2/quecloud-sdk-dev-msg-demonstration#1]
![image](https://user-images.githubusercontent.com/34028866/163081784-2032f4f3-3313-41b3-ba0c-05aac40dffde.png)
使用贵司SDK监听rabbitMq后，长时间不操作则会报错，报错信息如上图。
复现场景：我是从晚上下班开始挂，然后第二天早上来就一直报错了，这期间没有数据传输。

**Comment by thridparty-cloud2** [comment]
> ![image](https://user-images.githubusercontent.com/34028866/163081784-2032f4f3-3313-41b3-ba0c-05aac40dffde.png) 使用贵司SDK监听rabbitMq后，长时间不操作则会报错，报错信息如上图。 复现场景：我是从晚上下班开始挂，然后第二天早上来就一直报错了，这期间没有数据传输。

已解决。请重试。有问题可以进群讨论qq:832051178
